const $ = (id) => document.getElementById(id);

export const dom = {
    markdown:     $('mc-markdown'),
    cards:        $('mc-cards'),
    empty:        $('mc-preview-empty'),
    format:       $('mc-format'),
    exportPng:    $('mc-export-png'),
    exportJpg:    $('mc-export-jpg'),
    status:       $('mc-status'),
    drawer:       $('mc-drawer'),
    drawerOvl:    $('mc-drawer-overlay'),
    toggleDrawer: $('mc-toggle-drawer'),
    closeDrawer:  $('mc-close-drawer'),
    paletteGrid:  $('mc-theme-grid'),
    templateGrid: $('mc-template-grid'),
    resetBtn:     $('mc-reset'),
    shareBtn:     $('mc-share-config'),
    appearance:   $('mc-appearance'),
    langSwitch:   $('mc-lang'),
    h1: $('mc-h1'),     h1V: $('mc-h1-val'),
    h2: $('mc-h2'),     h2V: $('mc-h2-val'),
    h3: $('mc-h3'),     h3V: $('mc-h3-val'),
    body: $('mc-body'), bodyV: $('mc-body-val'),
    lh: $('mc-lh'),     lhV: $('mc-lh-val'),
    bg: $('mc-bg'),
    headC: $('mc-header-c'),
    bodyC: $('mc-body-c'),
    pad: $('mc-pad'),   padV: $('mc-pad-val'),
    my: $('mc-my'),     myV: $('mc-my-val'),
    bw: $('mc-bw'),     bwV: $('mc-bw-val'),
    bc: $('mc-bc'),
    br: $('mc-br'),     brV: $('mc-br-val'),
    watermark: $('mc-watermark'),
};
