const LAYOUTS = [
    {
        id: 'editorial-default',
        name: 'Editorial 默认',
        desc: '衬线体杂志排版，均衡适配通用分享',
        family: 'editorial',
        cssClass: 'mc--editorial-default',
        typography: {
            headingFont: 'var(--mc-font-serif)',
            bodyFont: 'var(--mc-font-serif)',
            monoFont: 'var(--mc-font-mono)',
            h1Weight: 500,
            h2Weight: 400,
            h3Weight: 400,
            headingTracking: '0.03em',
        },
        visual: {
            bgTreatment: 'paper',
            accentUsage: 'rule-only',
            cornerStyle: 'sharp',
            shadow: false,
            ruleStyle: 'hairline',
        },
        defaults: {
            pad: 26,
            my: 10,
            bw: 0,
            br: 0,
        },
    },
    {
        id: 'editorial-magazine',
        name: 'Editorial 杂志',
        desc: '强化杂志风格：衬线标题，通栏图片，上下装饰线',
        family: 'editorial',
        cssClass: 'mc--editorial-magazine',
        typography: {
            headingFont: 'var(--mc-font-serif)',
            bodyFont: 'var(--mc-font-serif)',
            monoFont: 'var(--mc-font-mono)',
            h1Weight: 500,
            h2Weight: 400,
            h3Weight: 400,
            headingTracking: '0.04em',
        },
        visual: {
            bgTreatment: 'paper',
            accentUsage: 'rule-only',
            cornerStyle: 'sharp',
            shadow: false,
            ruleStyle: 'hairline',
        },
        defaults: {
            pad: 40,
            my: 14,
            bw: 0,
            br: 0,
        },
    },
    {
        id: 'editorial-prose',
        name: 'Editorial 散文',
        desc: '长文布局：宽裕留白，衬线正文，适合深度阅读',
        family: 'editorial',
        cssClass: 'mc--editorial-prose',
        typography: {
            headingFont: 'var(--mc-font-serif)',
            bodyFont: 'var(--mc-font-serif)',
            monoFont: 'var(--mc-font-mono)',
            h1Weight: 500,
            h2Weight: 400,
            h3Weight: 400,
            headingTracking: '0.02em',
        },
        visual: {
            bgTreatment: 'paper',
            accentUsage: 'none',
            cornerStyle: 'sharp',
            shadow: false,
            ruleStyle: 'none',
        },
        defaults: {
            pad: 36, my: 12, bw: 0, br: 0,
            h1: 24, h2: 18, h3: 15,
            bodyFs: 15, lh: 1.6,
        },
    },
    {
        id: 'swiss-minimal',
        name: 'Swiss 极简',
        desc: '瑞士国际主义：轻字重无衬线，极简留白，适合文艺摘录',
        family: 'swiss',
        cssClass: 'mc--swiss-minimal',
        typography: {
            headingFont: 'var(--mc-font-sans)',
            bodyFont: 'var(--mc-font-sans)',
            monoFont: 'var(--mc-font-mono)',
            h1Weight: 300,
            h2Weight: 300,
            h3Weight: 400,
            headingTracking: '0.06em',
        },
        visual: {
            bgTreatment: 'flat',
            accentUsage: 'none',
            cornerStyle: 'sharp',
            shadow: false,
            ruleStyle: 'hairline',
        },
        defaults: {
            pad: 36,
            my: 10,
            bw: 0,
            br: 0,
        },
    },
    {
        id: 'swiss-card',
        name: 'Swiss 名片',
        desc: '名片卡片：圆角投影，适合正式场合分享',
        family: 'swiss',
        cssClass: 'mc--swiss-card',
        typography: {
            headingFont: 'var(--mc-font-sans)',
            bodyFont: 'var(--mc-font-sans)',
            monoFont: 'var(--mc-font-mono)',
            h1Weight: 400,
            h2Weight: 500,
            h3Weight: 600,
            headingTracking: '0em',
        },
        visual: {
            bgTreatment: 'flat',
            accentUsage: 'block',
            cornerStyle: 'rounded',
            shadow: true,
            ruleStyle: 'dashed',
        },
        defaults: {
            pad: 28, my: 8, bw: 0, br: 16,
            h1: 17, h2: 16, h3: 14,
            bodyFs: 14, lh: 1.35,
        },
    },
    {
        id: 'swiss-poster',
        name: 'Swiss 海报',
        desc: '海报风格：超大轻字重标题，单一强调色，适合观点输出',
        family: 'swiss',
        cssClass: 'mc--swiss-poster',
        typography: {
            headingFont: 'var(--mc-font-sans)',
            bodyFont: 'var(--mc-font-sans)',
            monoFont: 'var(--mc-font-mono)',
            h1Weight: 200,
            h2Weight: 300,
            h3Weight: 400,
            headingTracking: '-0.01em',
        },
        visual: {
            bgTreatment: 'flat',
            accentUsage: 'block',
            cornerStyle: 'sharp',
            shadow: false,
            ruleStyle: 'hairline',
        },
        defaults: {
            pad: 48, my: 28, bw: 0, br: 0,
            h1: 28, h2: 24, h3: 17,
            bodyFs: 16, lh: 1.35,
        },
    },
];

export const DEFAULT_LAYOUT = 'editorial-default';

export default LAYOUTS;
